repos:
  - repo: local
    hooks:
      - id: isort.cfg
        name: isort
        entry: isort --settings-file .isort.cfg
        language: system
        types: [python]
        pass_filenames: true
        exclude: .venv/

      - id: black
        name: black
        entry: black --config .black
        language: system
        types: [python]
        pass_filenames: true
        exclude: .venv/

      - id: flake8
        name: flake8
        entry: flake8 --config .flake
        language: system
        types: [python]
        pass_filenames: false
        exclude: .venv/
